language: go

go:
  - 1.9
  - master

go_import_path: github.com/rebuy-de/rebuy-go-sdk

before_install:
- GOFILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
- GOPKGS=$(go list ./...)
- curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
- go get golang.org/x/lint/golint

install:
- dep ensure

script:
- gofmt -l $GOFILES
- go build $GOPKGS
- go test -v $GOPKGS
- golint -set_exit_status $GOPKGS
