language: go

go:
  - 1.x

before_install:
- go get golang.org/x/lint/golint

install:
- cd v2
- go mod vendor

script:
- go build -o dist/buildutil-bootstrap ./cmd/buildutil
- ./dist/buildutil-bootstrap -v
    -x linux/amd64 -x darwin/amd64
    --s3-url s3://rebuy-github-releases/rebuy-go-sdk

cache:
  directories:
  - $GOPATH/pkg
  - $HOME/.cache/go-build
  - v2/vendor
