language: go

go:
  - 1.x

before_install:
- go get golang.org/x/lint/golint

install:
- cd v2

script:
- ./buildutilw build -v -x linux/amd64 -x darwin/amd64 -x windows/amd64

cache:
  directories:
  - $GOPATH/pkg
  - $HOME/.cache/go-build
  - v2/vendor
